name: workspace-devcontainer
services:
  app:
    image: songhuangcn/workspace:latest
    # build: .
    env_file:
      - .env
    environment:
      DOCKER_HOST: tcp://docker:2375
    depends_on:
      - docker
    ports:
      - "4096:4096"
    volumes:
      - ..:/workspace
      - ~/.ssh:/home/ubuntu/.ssh
      - ~/.gitconfig:/home/ubuntu/.gitconfig
      - ./agents:/home/ubuntu/.agents
      - ./config/opencode:/home/ubuntu/.config/opencode
      - ./config/.bash_aliases:/home/ubuntu/.bash_aliases
      - ./data/gh:/home/ubuntu/.config/gh
      - ./data/opencode:/home/ubuntu/.local/share/opencode
      - ./data/codex:/home/ubuntu/.codex
      - ./data/claude:/home/ubuntu/.claude
      - ./data/.claude.json:/home/ubuntu/.claude.json
      - ./data/vscode-server-extensions:/home/ubuntu/.vscode-server/extensions
      - ./data/vscode-server-data:/home/ubuntu/.vscode-server/data
  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - ..:/workspace
      - docker-data:/var/lib/docker

volumes:
  docker-data:
