name: workspace-devcontainer
services:
  app:
    image: songhuangcn/workspace:latest
    # build: .
    env_file:
      - .env
    ports:
      - "4096:4096"
    volumes:
      - ..:/workspace
      - ~/.ssh:/home/ubuntu/.ssh
      - ~/.gitconfig:/home/ubuntu/.gitconfig
      - ./agents:/home/ubuntu/.agents
      - ./config/opencode:/home/ubuntu/.config/opencode
      - ./config/gh:/home/ubuntu/.config/gh
      - ./data/opencode:/home/ubuntu/.local/share/opencode
      - ./data/vscode-server-extensions:/home/ubuntu/.vscode-server/extensions
      - ./data/vscode-server-data:/home/ubuntu/.vscode-server/data
      - ./data/claude:/home/ubuntu/.claude
      - ./data/claude.json:/home/ubuntu/.claude.json
